apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: demo-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: demo-issuer-account-key
    solvers:
    - http01:
        ingress: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-example-com
spec:
  secretName: nginx-example-com
  dnsNames:
  - nginx.example.com
  issuerRef:
    name: demo-issuer
    kind: Issuer